#!/usr/bin/env node
/* =============================================================================
   tools/vscode/generate.mjs
   -----------------------------------------------------------------------------
   Builds data/deck-data.json — everything the editor extension knows — from the
   files the main build already produces. Run it from this folder:

       node generate.mjs

   Nothing in the extension is hand-maintained. That is the entire point. A
   hand-kept class list is a list that goes stale the first time someone renames
   a class, and a stale IntelliSense list is worse than none: it autocompletes
   you into a class that no longer exists.

   Inputs, all generated by the main build:
     ../../dist/api.json          classes[], tokens[] — names, layers, docs,
                                  declarations, source file and line
     ../../dist/api-buckets.json  buckets.public / .internal, decisions{},
                                  removed[] with the reason each was dropped
     ../../dist/deck-icons.svg    the sprite, for its <symbol id> list
     ../../package.json           the version this data describes

   If any input is missing, this exits non-zero rather than writing a partial
   file. An extension shipping half a class list would flag real classes as
   typos, which is the one failure mode worse than having no diagnostics.
   ============================================================================= */

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '..', '..');
const out  = resolve(here, 'data', 'deck-data.json');

/* --- Read, or fail loudly ------------------------------------------------- */

function readJson(rel) {
  const p = resolve(repo, rel);
  if (!existsSync(p)) {
    console.error(`\n  ${rel} is missing.\n  Run \`npm run build\` in the repo root first.\n`);
    process.exit(1);
  }
  return JSON.parse(readFileSync(p, 'utf8'));
}

const api     = readJson('dist/api.json');
const buckets = readJson('dist/api-buckets.json');
const pkg     = readJson('package.json');

const spritePath = resolve(repo, 'dist/deck-icons.svg');
if (!existsSync(spritePath)) {
  console.error('\n  dist/deck-icons.svg is missing. Run `npm run build` first.\n');
  process.exit(1);
}
const sprite = readFileSync(spritePath, 'utf8');

/* --- Shape the class list ------------------------------------------------- *
   Only public classes get completions. Internal ones still get an entry, in
   their own map, so using one produces a warning rather than a silent pass —
   a consumer leaning on an internal class is depending on something that can
   change in a patch release.
   ---------------------------------------------------------------------- */

const byName  = new Map(api.classes.map((c) => [c.name, c]));
const publics = new Set(buckets.buckets.public);

/* Keep docs useful but bounded. The full prose lives in the docs site; a hover
   card wants the first thought, not the whole essay. */
const DOC_CAP = 700;
const trim = (s) => {
  if (!s) return null;
  const t = String(s).replace(/\s*\n\s*/g, ' ').trim();
  return t.length > DOC_CAP ? t.slice(0, DOC_CAP - 1).replace(/\s+\S*$/, '') + '…' : t;
};

/* For the 541 public classes with no prose, the declarations ARE the
   documentation: `position: absolute` says everything .absolute does. */
const declSummary = (c) =>
  (c.declarations || [])
    .slice(0, 8)
    .map((d) => `${d.prop}: ${d.value}`);

const classes = [];
for (const name of buckets.buckets.public) {
  const c = byName.get(name);
  if (!c) continue;
  classes.push({
    n:  name,
    l:  c.layer || null,
    f:  c.file || null,
    ln: c.line || null,
    d:  trim(c.doc),
    x:  declSummary(c),
    v:  (c.variants || []).slice(0, 24),
    /* A class defined only inside a media or container query behaves
       differently from an unconditional one, and that is worth saying on
       hover — it is why a utility can look like it does nothing. */
    cond: c.definedUnconditional === false ? true : undefined,
    /* State classes (.is-*) are applied by JavaScript, not written by hand.
       Saying so prevents a reader from hand-writing .is-copied and wondering
       why nothing happens. */
    role: c.role || undefined,
    owners: c.ownerClasses && c.ownerClasses.length ? c.ownerClasses.slice(0, 12) : undefined,
  });
}

/* --- Internal: allowed, but warn ----------------------------------------- */

const internal = {};
for (const name of buckets.buckets.internal) {
  const d = buckets.decisions[name];
  internal[name] = (d && d.reason) || 'Internal to Deck.';
}

/* --- Removed: error, with a replacement where the ledger names one -------- *
   30 of the 31 removed classes say what replaced them, in prose like
   "duplicate of .w-full". Parsing that out turns a diagnostic into a one-click
   fix, which is the difference between the extension telling you off and the
   extension doing the work.
   ---------------------------------------------------------------------- */

const REPLACEMENT = /(?:duplicate of|renamed to|replaced by|superseded by|use)\s+\.([a-z0-9][\w-]*)/i;

const removed = {};
for (const r of buckets.removed || []) {
  const m = REPLACEMENT.exec(r.reason || '');
  removed[r.name] = {
    reason: trim(r.reason) || 'Removed from Deck.',
    /* Only offer the fix if the named replacement is itself a real public
       class. A quick-fix that inserts another dead class is a trap. */
    replace: m && publics.has(m[1]) ? m[1] : null,
  };
}

/* --- Families -------------------------------------------------------------
   The data that makes unknown-class diagnostics precise instead of noisy, and
   the part of this file that took the most care to get right.

   A family root is a public class that other names extend: `stack` is a root
   because `stack-2` exists. The naive rule — flag any unknown token beginning
   with a root plus a dash — is too blunt. It flags `.phone-frame`, an author's
   own class that happens to share a prefix with Deck's `.phone` input, and an
   extension that underlines correct markup gets switched off within a day.

   So each root also carries its real sibling suffixes. `.stack`'s are
   1, 2, 3, 4, 6 and 8. An unknown `stack-5` has a numeric suffix in a family
   whose siblings are numeric, which is a near-certain mistake — and it is the
   exact bug this extension exists for, because `.stack-5` silently inherits
   the default gap and looks like it worked. An unknown `phone-frame` has the
   suffix `frame`, which resembles none of `.phone`'s siblings, so it is left
   alone.
   ---------------------------------------------------------------------- */

const families = {};
const noteRoot = (root, suffix) => {
  (families[root] ||= new Set()).add(suffix);
};

for (const name of publics) {
  /* Siblings discovered from the name itself: .stack-2 implies root .stack.
     The root need NOT be a class of its own — the spacing utilities are
     .gap-0 … .gap-8 with no bare .gap, and those are precisely the families
     where an off-the-scale number like .gap-5 does silent damage. */
  const i = name.lastIndexOf('-');
  if (i > 0) noteRoot(name.slice(0, i), name.slice(i + 1));

  /* And from the extractor's own variant list, which is authoritative. */
  for (const v of byName.get(name)?.variants || []) {
    if (v.startsWith(name + '-')) noteRoot(name, v.slice(name.length + 1));
  }
}

/* Freeze into a shippable shape. Two siblings minimum: a root inferred from a
   single class is not a family, it is a coincidence, and treating it as one is
   what flags an author's own `.phone-frame` against Deck's `.phone`. */
const familyOut = {};
for (const [root, set] of Object.entries(families)) {
  if (set.size < 2) continue;
  const suffixes = [...set].sort((a, b) =>
    /^\d+$/.test(a) && /^\d+$/.test(b) ? Number(a) - Number(b) : a.localeCompare(b));
  familyOut[root] = {
    s: suffixes,
    num: suffixes.some((s) => /^\d+$/.test(s)) || undefined,
  };
}

/* --- Tokens --------------------------------------------------------------- */

const tokens = api.tokens.map((t) => ({
  n:  t.name,
  v:  t.value,
  k:  t.kind || 'other',
  f:  t.file || null,
  ln: t.line || null,
  d:  trim(t.doc),
  g:  t.group || undefined,
  /* A token redefined under a condition (dark mode, forced colors) has more
     than one value; the hover says so rather than claiming the :root one. */
  cond: t.conditions && t.conditions.length ? true : undefined,
}));

/* --- Icons ---------------------------------------------------------------- */

const icons = [...sprite.matchAll(/<symbol[^>]*\bid="([^"]+)"/g)].map((m) => m[1]);
if (icons.length === 0) {
  console.error('\n  Parsed 0 symbols out of dist/deck-icons.svg. Refusing to write an empty icon list.\n');
  process.exit(1);
}

/* --- Write ---------------------------------------------------------------- */

const data = {
  generated: 'tools/vscode/generate.mjs — do not edit',
  version: pkg.version,
  counts: {
    public: classes.length,
    internal: Object.keys(internal).length,
    removed: Object.keys(removed).length,
    tokens: tokens.length,
    icons: icons.length,
    families: Object.keys(familyOut).length,
  },
  classes,
  internal,
  removed,
  tokens,
  icons,
  families: familyOut,
};

mkdirSync(dirname(out), { recursive: true });
writeFileSync(out, JSON.stringify(data), 'utf8');

const kb = (n) => (n / 1000).toFixed(1) + ' KB';
console.log(`
  data/deck-data.json written for Deck ${pkg.version}  (${kb(JSON.stringify(data).length)})

    ${String(data.counts.public).padStart(4)} public classes      completion + hover
    ${String(data.counts.internal).padStart(4)} internal classes    warn on use
    ${String(data.counts.removed).padStart(4)} removed classes     error, ${Object.values(removed).filter((r) => r.replace).length} with a quick-fix
    ${String(data.counts.tokens).padStart(4)} tokens              completion + swatch
    ${String(data.counts.icons).padStart(4)} icon symbols        completion after '#'
    ${String(data.counts.families).padStart(4)} family roots        unknown-class detection
`);
