/**
 * The static files that name the site's own host: sitemap.xml, robots.txt and
 * llms.txt.
 *
 * Pages ask PHP for the base URL (public_html/_site.php). These three are served
 * as they are, so build.mjs calls writeSiteFiles() to write the base into them,
 * resolved from the same inputs in the same order: DECK_SITE_BASE from the
 * environment, otherwise "homepage" in package.json. No URL is typed here.
 *
 * sitemap.xml is generated from the filesystem rather than kept by hand. It lists
 * every .php file under public_html/ except partials, whose names start with an
 * underscore, and anything under assets/. A page's entry is the URL that page
 * prints as its canonical, because a sitemap that disagrees with a page about
 * its own address leaves a search engine to pick one:
 *
 *   index.php        {base}/
 *   anything else    {base}/{path}      what docs/_layout.php prints for docs/{path}
 *
 * lastmod is the date of the last commit that touched the page, or today for a
 * page with uncommitted changes; outside a git checkout it is left out rather
 * than guessed. There is no changefreq or priority, because Google ignores both.
 *
 * As in tools/sync-sizes.mjs, every rewrite must match exactly once, and a check
 * that fails stops the build rather than leaving a stale file behind.
 */

import { readFile, writeFile, readdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import path from 'node:path';

const PUBLIC = 'public_html';

/** Links in llms.txt that point at the site, by link text. Each must appear once. */
const LLMS_LINKS = [
  ['Documentation site', '/docs/index.php'],
  ['Install page', '/docs/start/install.php'],
];

/** The same resolution as public_html/_site.php. */
export function siteBase(pkg) {
  const env = process.env.DECK_SITE_BASE;
  return {
    base: (env || pkg.homepage).replace(/\/+$/, ''),
    source: env ? 'DECK_SITE_BASE' : 'package.json homepage',
  };
}

/** Every page under public_html/, as a path relative to it, sorted. */
async function listPages(root) {
  const found = [];
  const walk = async (dir) => {
    const entries = await readdir(path.join(root, PUBLIC, dir), { withFileTypes: true });
    for (const entry of entries) {
      const rel = dir ? `${dir}/${entry.name}` : entry.name;
      if (entry.isDirectory()) {
        if (rel !== 'assets') await walk(rel);
      } else if (entry.name.endsWith('.php') && !entry.name.startsWith('_')) {
        found.push(rel);
      }
    }
  };
  await walk('');
  return found.sort();
}

const localDate = (d = new Date()) =>
  `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;

/** Page path, relative to public_html/ -> YYYY-MM-DD. Empty outside a git checkout. */
function lastModified(root) {
  const git = (...args) => execFileSync('git', args, {
    cwd: root, encoding: 'utf8', maxBuffer: 64 * 1024 * 1024, stdio: ['ignore', 'pipe', 'ignore'],
  });
  const prefix = `${PUBLIC}/`;
  const dates = new Map();
  try {
    // Newest commit first, so the first date seen for a file is its last change.
    let date = null;
    for (const raw of git('log', '--format=@@%cs', '--name-only', '--', PUBLIC).split('\n')) {
      const line = raw.trim();
      if (line.startsWith('@@')) date = line.slice(2);
      else if (date && line.startsWith(prefix)) {
        const rel = line.slice(prefix.length);
        if (!dates.has(rel)) dates.set(rel, date);
      }
    }
    const today = localDate();
    for (const raw of git('status', '--porcelain', '--untracked-files=all', '--', PUBLIC).split('\n')) {
      const file = raw.slice(3).split(' -> ').pop().trim();
      if (file.startsWith(prefix)) dates.set(file.slice(prefix.length), today);
    }
  } catch {
    return new Map();
  }
  return dates;
}

const escapeXml = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');

async function writeSitemap(root, base, source) {
  const pages = await listPages(root);
  const dates = lastModified(root);
  const entries = pages.map((rel) => {
    const loc = rel === 'index.php' ? `${base}/` : `${base}/${rel}`;
    const lastmod = dates.get(rel);
    return [
      '  <url>',
      `    <loc>${escapeXml(loc)}</loc>`,
      ...(lastmod ? [`    <lastmod>${lastmod}</lastmod>`] : []),
      '  </url>',
    ].join('\n');
  });
  const xml = [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!--',
    `  Generated by build.mjs (tools/site.mjs) from the ${pages.length} pages under public_html/.`,
    '  Do not edit it. Add or remove a page and the next build adds or removes it here.',
    `  Base URL: ${base}, from ${source}.`,
    '-->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...entries,
    '</urlset>',
    '',
  ].join('\n');
  await writeFile(path.join(root, PUBLIC, 'sitemap.xml'), xml);
  return pages.length;
}

/**
 * robots.txt as groups: a run of User-agent lines, then the rules under them.
 * Comments and blank lines do not end a group; the next User-agent after a rule does.
 */
function robotsGroups(text) {
  const groups = [];
  let group = null;
  let inAgents = false;
  for (const raw of text.split(/\r?\n/)) {
    const m = /^\s*([A-Za-z-]+)\s*:\s*(.*?)\s*$/.exec(raw.replace(/#.*/, ''));
    if (!m) continue;
    const field = m[1].toLowerCase();
    if (field === 'user-agent') {
      if (!inAgents) groups.push(group = { agents: [], rules: [] });
      group.agents.push(m[2]);
      inAgents = true;
    } else {
      inAgents = false;
      if (group && (field === 'allow' || field === 'disallow')) group.rules.push(`${field}: ${m[2]}`);
    }
  }
  return groups;
}

async function syncRobots(root, base) {
  const rel = `${PUBLIC}/robots.txt`;
  const file = path.join(root, rel);
  let text = await readFile(file, 'utf8');

  const sitemap = /^Sitemap:.*$/gm;
  const hits = text.match(sitemap);
  if (!hits || hits.length !== 1) {
    throw new Error(`site: ${rel} has ${hits ? hits.length : 0} Sitemap lines, expected exactly 1.`);
  }
  text = text.replace(sitemap, `Sitemap: ${base}/sitemap.xml`);

  // A crawler obeys only the group that names it and never reads *, so a rule
  // that is not repeated in its own group does not apply to it.
  const groups = robotsGroups(text);
  const star = groups.find((g) => g.agents.includes('*'));
  if (!star) throw new Error(`site: ${rel} has no "User-agent: *" group.`);
  const rules = (g) => [...g.rules].sort().join('\n');
  const differ = groups.filter((g) => rules(g) !== rules(star));
  if (differ.length) {
    throw new Error(
      `site: ${differ.length} group${differ.length === 1 ? '' : 's'} in ${rel} ` +
      'carry different rules from the * group. A crawler with its own group never reads *, ' +
      'so every group has to repeat the same rules:\n' +
      differ.map((g) => `    ${g.agents.join(', ')}: ${g.rules.join('; ') || '(no rules)'}`).join('\n')
    );
  }

  await writeFile(file, text);
  return groups;
}

async function syncLlms(root, base) {
  const rel = `${PUBLIC}/llms.txt`;
  const file = path.join(root, rel);
  let text = await readFile(file, 'utf8');
  for (const [label, page] of LLMS_LINKS) {
    const link = new RegExp(`\\[${label}\\]\\([^)]*\\)`, 'g');
    const hits = text.match(link);
    if (!hits || hits.length !== 1) {
      throw new Error(
        `site: the [${label}] link matched ${hits ? hits.length : 0} times in ${rel}, expected exactly 1. ` +
        'Update LLMS_LINKS in tools/site.mjs if the link text changed.'
      );
    }
    text = text.replace(link, `[${label}](${base}${page})`);
  }
  await writeFile(file, text);
  return LLMS_LINKS.length;
}

/** npm and Packagist should send people to the same site. */
async function checkHomepages(root, pkg) {
  const composer = JSON.parse(await readFile(path.join(root, 'composer.json'), 'utf8'));
  if (composer.homepage !== pkg.homepage) {
    throw new Error(
      `site: composer.json homepage is ${composer.homepage}, package.json homepage is ${pkg.homepage}. ` +
      'Make them match.'
    );
  }
}

export async function writeSiteFiles(pkg, root) {
  const { base, source } = siteBase(pkg);
  await checkHomepages(root, pkg);
  const pages = await writeSitemap(root, base, source);
  const groups = await syncRobots(root, base);
  const links = await syncLlms(root, base);
  return { base, source, pages, groups: groups.length, agents: groups.flatMap((g) => g.agents), links };
}
